const App = {
  state: {products:[], categories:[]},
  currency(value){ return value == null ? "—" : new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(value); },
  img(src){ return src || "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='600' height='600'%3E%3Crect width='100%25' height='100%25' fill='%23f3f4f6'/%3E%3Cpath d='M210 400l80-95 55 60 45-52 90 87H210z' fill='%23d1d5db'/%3E%3Ccircle cx='390' cy='230' r='45' fill='%23d1d5db'/%3E%3C/svg%3E"; },
  escape(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));},
  productCard(p){
    const id=p.id||p._id; return `<article class="product-card">
      <a href="#/product/${encodeURIComponent(id)}"><div class="product-image"><img loading="lazy" src="${this.escape(this.img(p.image||p.images?.[0]?.url||p.images?.[0]))}" alt="${this.escape(p.name||"Product")}">
      ${p.sold?'<span class="status-badge">Sold</span>':''}<button class="heart" data-fav="${this.escape(id)}" aria-label="Favorite"><i class="fa-regular fa-heart"></i></button></div>
      <div class="card-body"><div class="product-name">${this.escape(p.name||"Unnamed product")}</div><div class="price">${this.currency(p.price)}</div><div class="meta">${this.escape(p.location||p.category||"")}</div></div></a>
    </article>`;
  },
  async home(){
    const root=document.getElementById("app");
    root.innerHTML=`<section class="hero"><div class="container hero-grid">
      <div class="hero-main"><span class="eyebrow">SHINEX Marketplace</span><h1>Find it.<br>Buy it. Sell it.</h1>
      <p>A simple marketplace for discovering products from real sellers. No fake listings. No clutter.</p>
      <form id="heroSearch" class="hero-search"><input name="q" placeholder="What are you looking for?" aria-label="Search products"><button class="btn btn-primary">Search</button></form></div>
      <aside class="hero-side"><div><span class="eyebrow">For sellers</span><h2>Turn unused items into money.</h2><p>List your products and connect directly with interested buyers.</p></div><a class="btn btn-primary" href="#/sell">Start selling</a></aside>
    </div></section>
    <section class="section"><div class="container"><div class="section-head"><h2>Categories</h2></div><div id="categories" class="categories"><span class="muted">Loading…</span></div></div></section>
    <section class="section"><div class="container"><div class="section-head"><h2>Latest products</h2><a class="muted" href="#/search">View all</a></div><div id="products" class="grid">${[1,2,3,4].map(()=>'<div class="skeleton"></div>').join("")}</div></div></section>`;
    document.getElementById("heroSearch").onsubmit=e=>{e.preventDefault(); location.hash="/search?q="+encodeURIComponent(new FormData(e.currentTarget).get("q"));};
    try {
      const [cats, products]=await Promise.all([API.get("/categories"),API.get("/products?limit=8")]);
      const categories=Array.isArray(cats)?cats:(cats?.categories||[]);
      const list=Array.isArray(products)?products:(products?.products||products?.data||[]);
      document.getElementById("categories").innerHTML=categories.length?categories.map(c=>`<a class="category" href="#/search?category=${encodeURIComponent(c.id||c._id||c.name)}">${this.escape(c.name||c.title)}</a>`).join(""):`<span class="muted">No categories available yet.</span>`;
      document.getElementById("products").innerHTML=list.length?list.map(p=>this.productCard(p)).join(""):`<div class="empty" style="grid-column:1/-1">No products available yet.</div>`;
    } catch(e){ document.getElementById("products").innerHTML=`<div class="error" style="grid-column:1/-1">Marketplace could not load. Please check your internet connection and try again.<br><button class="btn btn-secondary btn-small" onclick="location.reload()">Retry</button></div>`; }
  },
  async search(params){
    const root=document.getElementById("app"); root.innerHTML=`<section class="page"><div class="container"><div class="section-head"><div><h1>Search</h1><p class="muted">Results from the marketplace.</p></div></div><div id="results" class="grid"><div class="skeleton"></div><div class="skeleton"></div></div></div></section>`;
    const qs=new URLSearchParams(params).toString();
    try{const r=await API.get("/products?"+qs);const list=Array.isArray(r)?r:(r?.products||r?.data||[]);document.getElementById("results").innerHTML=list.length?list.map(p=>this.productCard(p)).join(""):`<div class="empty" style="grid-column:1/-1">No products found.</div>`}
    catch(e){document.getElementById("results").innerHTML=`<div class="error" style="grid-column:1/-1">Unable to load search results. <button class="btn btn-secondary btn-small" onclick="location.reload()">Retry</button></div>`}
  },
  async product(id){
    const root=document.getElementById("app");root.innerHTML=`<section class="page"><div class="container"><div class="skeleton" style="height:500px"></div></div></section>`;
    try{const r=await API.get("/products/"+encodeURIComponent(id));const p=r?.product||r?.data||r;const imgs=(p.images||[]).map(x=>typeof x==="string"?x:x.url).filter(Boolean);if(p.image&&!imgs.length)imgs.push(p.image);const main=this.img(imgs[0]);
      root.innerHTML=`<section class="page"><div class="container detail"><div><div class="gallery-main"><img id="mainImage" src="${this.escape(main)}" alt="${this.escape(p.name)}"></div><div class="thumbs">${imgs.map((x,i)=>`<img class="${i===0?"active":""}" data-src="${this.escape(x)}" src="${this.escape(x)}" alt="">`).join("")}</div></div>
      <div><span class="eyebrow">${this.escape(p.category||"Marketplace")}</span><h1>${this.escape(p.name)}</h1><div class="detail-price">${this.currency(p.price)}</div><div class="detail-info"><div><i class="fa-solid fa-location-dot"></i> ${this.escape(p.location||"Location unavailable")}</div><div><i class="fa-regular fa-user"></i> ${this.escape(p.seller?.name||p.sellerName||"Seller")}</div><div>${p.available===false?"Out of stock":"Available"}</div></div><p class="muted" style="line-height:1.7">${this.escape(p.description||"No description provided.")}</p><div class="cta-row"><a class="btn btn-teal" id="wa" href="#" target="_blank" rel="noopener"><i class="fa-brands fa-whatsapp"></i> Contact Seller</a><button class="btn btn-secondary" id="share"><i class="fa-solid fa-share-nodes"></i> Share</button></div></div></div></section>`;
      document.querySelectorAll(".thumbs img").forEach(t=>t.onclick=()=>{document.getElementById("mainImage").src=t.dataset.src;document.querySelectorAll(".thumbs img").forEach(x=>x.classList.remove("active"));t.classList.add("active")});
      const phone=p.seller?.whatsapp||p.seller?.phone||p.whatsapp; if(phone){const clean=String(phone).replace(/\D/g,"");document.getElementById("wa").href=`https://wa.me/${clean}?text=${encodeURIComponent(`Hi, I'm interested in ${p.name} on SHINEX Marketplace.`)}`}else document.getElementById("wa").onclick=e=>{e.preventDefault();alert("Seller WhatsApp contact is not available.")};
      document.getElementById("share").onclick=()=>navigator.share?navigator.share({title:p.name,url:location.href}):navigator.clipboard?.writeText(location.href);
    }catch(e){root.innerHTML=`<section class="page"><div class="container"><div class="error">Product could not be loaded.</div></div></section>`}
  },
  page(title,body){document.getElementById("app").innerHTML=`<section class="page"><div class="container"><h1>${title}</h1>${body}</div></section>`},
  auth(type){this.page(type==="login"?"Login":"Create your SHINEX account",`<div class="auth"><div class="panel"><form class="form" id="authForm">
    ${type==="register"?'<div class="field"><label>Full name</label><input name="fullName" required></div><div class="field"><label>Username</label><input name="username" required></div><div class="field"><label>Phone</label><input name="phone" required></div>':''}
    <div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Password</label><input name="password" type="password" required></div>
    ${type==="register"?'<div class="field"><label>Confirm password</label><input name="confirmPassword" type="password" required></div><label class="muted"><input type="checkbox" required> I accept the terms.</label>':''}
    <button class="btn btn-primary" type="submit">${type==="login"?"Login":"Create account"}</button><div id="authMsg" class="notice" hidden></div>
    </form></div></div>`);
    document.getElementById("authForm").onsubmit=async e=>{e.preventDefault();const btn=e.currentTarget.querySelector("button");btn.disabled=true;btn.textContent="Please wait…";try{const data=Object.fromEntries(new FormData(e.currentTarget));const r=await API.post(type==="login"?"/auth/login":"/auth/register",data);document.getElementById("authMsg").hidden=false;document.getElementById("authMsg").textContent=r?.message||"Success.";if(type==="login")setTimeout(()=>location.hash="/home",700)}catch(err){document.getElementById("authMsg").hidden=false;document.getElementById("authMsg").textContent=err.message}finally{btn.disabled=false;btn.textContent=type==="login"?"Login":"Create account"}}
  },
  advertise(){this.page("Advertise",`<div class="panel"><p class="muted">Choose a duration supplied by the backend. Prices are never trusted from the browser.</p><form id="adForm" class="form"><div class="field"><label>Advertisement title</label><input name="title" required></div><div class="field"><label>Description</label><textarea name="description" required></textarea></div><div class="field"><label>Flyer/image</label><input name="image" type="file" accept="image/*" required></div><div class="field"><label>Duration</label><select id="duration" name="durationId" required><option>Loading pricing…</option></select></div><div id="adTotal" class="notice">Select a duration to see the total.</div><button class="btn btn-primary btn-small" type="submit">Pay with Paystack</button></form></div>`);
    (async()=>{try{const r=await API.get("/advertisements/pricing");const items=Array.isArray(r)?r:(r?.pricing||r?.data||[]);const s=document.getElementById("duration");s.innerHTML=items.length?items.map(x=>`<option value="${this.escape(x.id||x._id)}" data-price="${x.price}">${this.escape(x.duration||x.label||x.days+" days")} — ${this.currency(x.price)}</option>`).join(""):"<option>No advertising options available</option>";s.onchange=()=>{const o=s.selectedOptions[0];document.getElementById("adTotal").textContent=o?.dataset.price?`Total: ${this.currency(o.dataset.price)}`:"Select a duration to see the total."};}catch(e){document.getElementById("duration").innerHTML="<option>Pricing unavailable</option>"} })();
  },
  async sell(){this.page("Sell a product",`<div class="panel"><form id="sellForm" class="form"><div class="field"><label>Product name</label><input name="name" required></div><div class="field"><label>Description</label><textarea name="description" required></textarea></div><div class="field"><label>Price (NGN)</label><input name="price" type="number" min="0" required></div><div class="field"><label>Category</label><input name="category" required></div><div class="field"><label>Location</label><input name="location" required></div><div class="field"><label>Product images</label><input name="images" type="file" accept="image/*" multiple required></div><button class="btn btn-primary" type="submit">Publish product</button><div id="sellMsg" class="notice" hidden></div></form></div>`);
    document.getElementById("sellForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),m=document.getElementById("sellMsg");try{const r=await API.post("/products",f,{headers:{}});m.hidden=false;m.textContent=r?.message||"Product submitted successfully."}catch(err){m.hidden=false;m.textContent=err.message}};
  },
  staticPage(path){const content={about:["About SHINEX","SHINEX is a marketplace designed to make buying and selling simple, direct and trustworthy."],"contact":["Contact","<p>Email: <a href='mailto:shinexlearning@gmail.com'>shinexlearning@gmail.com</a></p><p>Phone: <a href='tel:+2347067574479'>+234 706 757 4479</a></p><p>WhatsApp: <a href='https://wa.me/2348025052852' target='_blank'>+234 802 505 2852</a></p>"],"privacy-policy":["Privacy Policy","<p>SHINEX should display its current privacy policy here. Connect this page to the final policy content before launch.</p>"],"terms":["Terms & Conditions","<p>SHINEX should display its current terms here. Connect this page to the final terms content before launch.</p>"]};const [t,b]=content[path]||["Page not found","<p>The page you requested could not be found.</p>"];this.page(t,`<div class="panel" style="line-height:1.8">${b}</div>`)},
  init(){document.getElementById("year").textContent=new Date().getFullYear();const saved=localStorage.getItem("shinex-theme");if(saved==="dark")document.body.classList.add("dark")}
}; App.init();